/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SovereignGoldBondsGuideRouteImport } from './routes/sovereign-gold-bonds-guide'
import { Route as SipCalculatorRouteImport } from './routes/sip-calculator'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrdRouteImport } from './routes/prd'
import { Route as LumpsumCalculatorRouteImport } from './routes/lumpsum-calculator'
import { Route as GoldTaxationRouteImport } from './routes/gold-taxation'
import { Route as GoldMutualFundsRouteImport } from './routes/gold-mutual-funds'
import { Route as GoldMiningStocksRouteImport } from './routes/gold-mining-stocks'
import { Route as GoldEtfsRouteImport } from './routes/gold-etfs'
import { Route as GoldAndInflationRouteImport } from './routes/gold-and-inflation'
import { Route as FuturesAndOptionsRouteImport } from './routes/futures-and-options'
import { Route as DigitalVsPhysicalGoldRouteImport } from './routes/digital-vs-physical-gold'
import { Route as BuyPhysicalGoldRouteImport } from './routes/buy-physical-gold'
import { Route as BeginnersGuideRouteImport } from './routes/beginners-guide'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsGoalPlannerRouteImport } from './routes/tools/goal-planner'
import { Route as ToolsFutureValueRouteImport } from './routes/tools/future-value'

const SovereignGoldBondsGuideRoute = SovereignGoldBondsGuideRouteImport.update({
  id: '/sovereign-gold-bonds-guide',
  path: '/sovereign-gold-bonds-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SipCalculatorRoute = SipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdRoute = PrdRouteImport.update({
  id: '/prd',
  path: '/prd',
  getParentRoute: () => rootRouteImport,
} as any)
const LumpsumCalculatorRoute = LumpsumCalculatorRouteImport.update({
  id: '/lumpsum-calculator',
  path: '/lumpsum-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldTaxationRoute = GoldTaxationRouteImport.update({
  id: '/gold-taxation',
  path: '/gold-taxation',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldMutualFundsRoute = GoldMutualFundsRouteImport.update({
  id: '/gold-mutual-funds',
  path: '/gold-mutual-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldMiningStocksRoute = GoldMiningStocksRouteImport.update({
  id: '/gold-mining-stocks',
  path: '/gold-mining-stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldEtfsRoute = GoldEtfsRouteImport.update({
  id: '/gold-etfs',
  path: '/gold-etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldAndInflationRoute = GoldAndInflationRouteImport.update({
  id: '/gold-and-inflation',
  path: '/gold-and-inflation',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesAndOptionsRoute = FuturesAndOptionsRouteImport.update({
  id: '/futures-and-options',
  path: '/futures-and-options',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalVsPhysicalGoldRoute = DigitalVsPhysicalGoldRouteImport.update({
  id: '/digital-vs-physical-gold',
  path: '/digital-vs-physical-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyPhysicalGoldRoute = BuyPhysicalGoldRouteImport.update({
  id: '/buy-physical-gold',
  path: '/buy-physical-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnersGuideRoute = BeginnersGuideRouteImport.update({
  id: '/beginners-guide',
  path: '/beginners-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGoalPlannerRoute = ToolsGoalPlannerRouteImport.update({
  id: '/tools/goal-planner',
  path: '/tools/goal-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFutureValueRoute = ToolsFutureValueRouteImport.update({
  id: '/tools/future-value',
  path: '/tools/future-value',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beginners-guide': typeof BeginnersGuideRoute
  '/buy-physical-gold': typeof BuyPhysicalGoldRoute
  '/digital-vs-physical-gold': typeof DigitalVsPhysicalGoldRoute
  '/futures-and-options': typeof FuturesAndOptionsRoute
  '/gold-and-inflation': typeof GoldAndInflationRoute
  '/gold-etfs': typeof GoldEtfsRoute
  '/gold-mining-stocks': typeof GoldMiningStocksRoute
  '/gold-mutual-funds': typeof GoldMutualFundsRoute
  '/gold-taxation': typeof GoldTaxationRoute
  '/lumpsum-calculator': typeof LumpsumCalculatorRoute
  '/prd': typeof PrdRoute
  '/profile': typeof ProfileRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/sovereign-gold-bonds-guide': typeof SovereignGoldBondsGuideRoute
  '/tools/future-value': typeof ToolsFutureValueRoute
  '/tools/goal-planner': typeof ToolsGoalPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beginners-guide': typeof BeginnersGuideRoute
  '/buy-physical-gold': typeof BuyPhysicalGoldRoute
  '/digital-vs-physical-gold': typeof DigitalVsPhysicalGoldRoute
  '/futures-and-options': typeof FuturesAndOptionsRoute
  '/gold-and-inflation': typeof GoldAndInflationRoute
  '/gold-etfs': typeof GoldEtfsRoute
  '/gold-mining-stocks': typeof GoldMiningStocksRoute
  '/gold-mutual-funds': typeof GoldMutualFundsRoute
  '/gold-taxation': typeof GoldTaxationRoute
  '/lumpsum-calculator': typeof LumpsumCalculatorRoute
  '/prd': typeof PrdRoute
  '/profile': typeof ProfileRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/sovereign-gold-bonds-guide': typeof SovereignGoldBondsGuideRoute
  '/tools/future-value': typeof ToolsFutureValueRoute
  '/tools/goal-planner': typeof ToolsGoalPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beginners-guide': typeof BeginnersGuideRoute
  '/buy-physical-gold': typeof BuyPhysicalGoldRoute
  '/digital-vs-physical-gold': typeof DigitalVsPhysicalGoldRoute
  '/futures-and-options': typeof FuturesAndOptionsRoute
  '/gold-and-inflation': typeof GoldAndInflationRoute
  '/gold-etfs': typeof GoldEtfsRoute
  '/gold-mining-stocks': typeof GoldMiningStocksRoute
  '/gold-mutual-funds': typeof GoldMutualFundsRoute
  '/gold-taxation': typeof GoldTaxationRoute
  '/lumpsum-calculator': typeof LumpsumCalculatorRoute
  '/prd': typeof PrdRoute
  '/profile': typeof ProfileRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/sovereign-gold-bonds-guide': typeof SovereignGoldBondsGuideRoute
  '/tools/future-value': typeof ToolsFutureValueRoute
  '/tools/goal-planner': typeof ToolsGoalPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beginners-guide'
    | '/buy-physical-gold'
    | '/digital-vs-physical-gold'
    | '/futures-and-options'
    | '/gold-and-inflation'
    | '/gold-etfs'
    | '/gold-mining-stocks'
    | '/gold-mutual-funds'
    | '/gold-taxation'
    | '/lumpsum-calculator'
    | '/prd'
    | '/profile'
    | '/sip-calculator'
    | '/sovereign-gold-bonds-guide'
    | '/tools/future-value'
    | '/tools/goal-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beginners-guide'
    | '/buy-physical-gold'
    | '/digital-vs-physical-gold'
    | '/futures-and-options'
    | '/gold-and-inflation'
    | '/gold-etfs'
    | '/gold-mining-stocks'
    | '/gold-mutual-funds'
    | '/gold-taxation'
    | '/lumpsum-calculator'
    | '/prd'
    | '/profile'
    | '/sip-calculator'
    | '/sovereign-gold-bonds-guide'
    | '/tools/future-value'
    | '/tools/goal-planner'
  id:
    | '__root__'
    | '/'
    | '/beginners-guide'
    | '/buy-physical-gold'
    | '/digital-vs-physical-gold'
    | '/futures-and-options'
    | '/gold-and-inflation'
    | '/gold-etfs'
    | '/gold-mining-stocks'
    | '/gold-mutual-funds'
    | '/gold-taxation'
    | '/lumpsum-calculator'
    | '/prd'
    | '/profile'
    | '/sip-calculator'
    | '/sovereign-gold-bonds-guide'
    | '/tools/future-value'
    | '/tools/goal-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeginnersGuideRoute: typeof BeginnersGuideRoute
  BuyPhysicalGoldRoute: typeof BuyPhysicalGoldRoute
  DigitalVsPhysicalGoldRoute: typeof DigitalVsPhysicalGoldRoute
  FuturesAndOptionsRoute: typeof FuturesAndOptionsRoute
  GoldAndInflationRoute: typeof GoldAndInflationRoute
  GoldEtfsRoute: typeof GoldEtfsRoute
  GoldMiningStocksRoute: typeof GoldMiningStocksRoute
  GoldMutualFundsRoute: typeof GoldMutualFundsRoute
  GoldTaxationRoute: typeof GoldTaxationRoute
  LumpsumCalculatorRoute: typeof LumpsumCalculatorRoute
  PrdRoute: typeof PrdRoute
  ProfileRoute: typeof ProfileRoute
  SipCalculatorRoute: typeof SipCalculatorRoute
  SovereignGoldBondsGuideRoute: typeof SovereignGoldBondsGuideRoute
  ToolsFutureValueRoute: typeof ToolsFutureValueRoute
  ToolsGoalPlannerRoute: typeof ToolsGoalPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sovereign-gold-bonds-guide': {
      id: '/sovereign-gold-bonds-guide'
      path: '/sovereign-gold-bonds-guide'
      fullPath: '/sovereign-gold-bonds-guide'
      preLoaderRoute: typeof SovereignGoldBondsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip-calculator': {
      id: '/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/sip-calculator'
      preLoaderRoute: typeof SipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd': {
      id: '/prd'
      path: '/prd'
      fullPath: '/prd'
      preLoaderRoute: typeof PrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumpsum-calculator': {
      id: '/lumpsum-calculator'
      path: '/lumpsum-calculator'
      fullPath: '/lumpsum-calculator'
      preLoaderRoute: typeof LumpsumCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-taxation': {
      id: '/gold-taxation'
      path: '/gold-taxation'
      fullPath: '/gold-taxation'
      preLoaderRoute: typeof GoldTaxationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-mutual-funds': {
      id: '/gold-mutual-funds'
      path: '/gold-mutual-funds'
      fullPath: '/gold-mutual-funds'
      preLoaderRoute: typeof GoldMutualFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-mining-stocks': {
      id: '/gold-mining-stocks'
      path: '/gold-mining-stocks'
      fullPath: '/gold-mining-stocks'
      preLoaderRoute: typeof GoldMiningStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-etfs': {
      id: '/gold-etfs'
      path: '/gold-etfs'
      fullPath: '/gold-etfs'
      preLoaderRoute: typeof GoldEtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-and-inflation': {
      id: '/gold-and-inflation'
      path: '/gold-and-inflation'
      fullPath: '/gold-and-inflation'
      preLoaderRoute: typeof GoldAndInflationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures-and-options': {
      id: '/futures-and-options'
      path: '/futures-and-options'
      fullPath: '/futures-and-options'
      preLoaderRoute: typeof FuturesAndOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-vs-physical-gold': {
      id: '/digital-vs-physical-gold'
      path: '/digital-vs-physical-gold'
      fullPath: '/digital-vs-physical-gold'
      preLoaderRoute: typeof DigitalVsPhysicalGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-physical-gold': {
      id: '/buy-physical-gold'
      path: '/buy-physical-gold'
      fullPath: '/buy-physical-gold'
      preLoaderRoute: typeof BuyPhysicalGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginners-guide': {
      id: '/beginners-guide'
      path: '/beginners-guide'
      fullPath: '/beginners-guide'
      preLoaderRoute: typeof BeginnersGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/goal-planner': {
      id: '/tools/goal-planner'
      path: '/tools/goal-planner'
      fullPath: '/tools/goal-planner'
      preLoaderRoute: typeof ToolsGoalPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/future-value': {
      id: '/tools/future-value'
      path: '/tools/future-value'
      fullPath: '/tools/future-value'
      preLoaderRoute: typeof ToolsFutureValueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeginnersGuideRoute: BeginnersGuideRoute,
  BuyPhysicalGoldRoute: BuyPhysicalGoldRoute,
  DigitalVsPhysicalGoldRoute: DigitalVsPhysicalGoldRoute,
  FuturesAndOptionsRoute: FuturesAndOptionsRoute,
  GoldAndInflationRoute: GoldAndInflationRoute,
  GoldEtfsRoute: GoldEtfsRoute,
  GoldMiningStocksRoute: GoldMiningStocksRoute,
  GoldMutualFundsRoute: GoldMutualFundsRoute,
  GoldTaxationRoute: GoldTaxationRoute,
  LumpsumCalculatorRoute: LumpsumCalculatorRoute,
  PrdRoute: PrdRoute,
  ProfileRoute: ProfileRoute,
  SipCalculatorRoute: SipCalculatorRoute,
  SovereignGoldBondsGuideRoute: SovereignGoldBondsGuideRoute,
  ToolsFutureValueRoute: ToolsFutureValueRoute,
  ToolsGoalPlannerRoute: ToolsGoalPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
