/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SipCalculatorRouteImport } from './routes/sip-calculator'
import { Route as LumpsumCalculatorRouteImport } from './routes/lumpsum-calculator'
import { Route as DigitalVsPhysicalGoldRouteImport } from './routes/digital-vs-physical-gold'
import { Route as BeginnersGuideRouteImport } from './routes/beginners-guide'
import { Route as IndexRouteImport } from './routes/index'

const SipCalculatorRoute = SipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LumpsumCalculatorRoute = LumpsumCalculatorRouteImport.update({
  id: '/lumpsum-calculator',
  path: '/lumpsum-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalVsPhysicalGoldRoute = DigitalVsPhysicalGoldRouteImport.update({
  id: '/digital-vs-physical-gold',
  path: '/digital-vs-physical-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnersGuideRoute = BeginnersGuideRouteImport.update({
  id: '/beginners-guide',
  path: '/beginners-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beginners-guide': typeof BeginnersGuideRoute
  '/digital-vs-physical-gold': typeof DigitalVsPhysicalGoldRoute
  '/lumpsum-calculator': typeof LumpsumCalculatorRoute
  '/sip-calculator': typeof SipCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beginners-guide': typeof BeginnersGuideRoute
  '/digital-vs-physical-gold': typeof DigitalVsPhysicalGoldRoute
  '/lumpsum-calculator': typeof LumpsumCalculatorRoute
  '/sip-calculator': typeof SipCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beginners-guide': typeof BeginnersGuideRoute
  '/digital-vs-physical-gold': typeof DigitalVsPhysicalGoldRoute
  '/lumpsum-calculator': typeof LumpsumCalculatorRoute
  '/sip-calculator': typeof SipCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beginners-guide'
    | '/digital-vs-physical-gold'
    | '/lumpsum-calculator'
    | '/sip-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beginners-guide'
    | '/digital-vs-physical-gold'
    | '/lumpsum-calculator'
    | '/sip-calculator'
  id:
    | '__root__'
    | '/'
    | '/beginners-guide'
    | '/digital-vs-physical-gold'
    | '/lumpsum-calculator'
    | '/sip-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeginnersGuideRoute: typeof BeginnersGuideRoute
  DigitalVsPhysicalGoldRoute: typeof DigitalVsPhysicalGoldRoute
  LumpsumCalculatorRoute: typeof LumpsumCalculatorRoute
  SipCalculatorRoute: typeof SipCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sip-calculator': {
      id: '/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/sip-calculator'
      preLoaderRoute: typeof SipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumpsum-calculator': {
      id: '/lumpsum-calculator'
      path: '/lumpsum-calculator'
      fullPath: '/lumpsum-calculator'
      preLoaderRoute: typeof LumpsumCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-vs-physical-gold': {
      id: '/digital-vs-physical-gold'
      path: '/digital-vs-physical-gold'
      fullPath: '/digital-vs-physical-gold'
      preLoaderRoute: typeof DigitalVsPhysicalGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginners-guide': {
      id: '/beginners-guide'
      path: '/beginners-guide'
      fullPath: '/beginners-guide'
      preLoaderRoute: typeof BeginnersGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeginnersGuideRoute: BeginnersGuideRoute,
  DigitalVsPhysicalGoldRoute: DigitalVsPhysicalGoldRoute,
  LumpsumCalculatorRoute: LumpsumCalculatorRoute,
  SipCalculatorRoute: SipCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
